# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jpalczewski gitblog
email: jpalczewski@gmail.com
description: Yet another github blog. Do you really think, that there will be something interesing? If yes, you're goddamn right.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jpalczewski.github.io" # the base hostname & protocol for your site
github_username: jpalczewski

# Build settings
markdown: kramdown
