# Site settings
title: jpalczewski
header-img: img/home-bg.jpg
email: jpalczewski@gmail.com
description: "jpalczewski blog, really!"
#baseurl: "/"
url: "http://jpalczewski.github.io"
github_username: jpalczewski
#facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
